USE RoommateManager;


IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('THANHVIEN') AND name = 'MATKHAU')
    ALTER TABLE THANHVIEN ADD MATKHAU NVARCHAR(200) NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('THANHVIEN') AND name = 'SOLANSAT')
    ALTER TABLE THANHVIEN ADD SOLANSAT INT DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('THANHVIEN') AND name = 'THOIGIANKHOA')
    ALTER TABLE THANHVIEN ADD THOIGIANKHOA DATETIME NULL;


IF NOT EXISTS (SELECT 1 FROM NHA WHERE MANHA = 'NH001')
    INSERT INTO NHA (MANHA, SONHA, DUONG, PHUONG, TP)
    VALUES ('NH001', '12', N'Nguyễn Văn Cừ', N'Phường 4', N'TP.HCM');

IF NOT EXISTS (SELECT 1 FROM THANHVIEN WHERE USERNAME = 'admin')
    INSERT INTO THANHVIEN (ID, TEN, MANHA, CON, USERNAME, MATKHAU, SOLANSAT, AD)
    VALUES ('TV001', N'Minh Nhật', 'NH001', 1, 'admin', '123456', 0, 1);

IF NOT EXISTS (SELECT 1 FROM THANHVIEN WHERE USERNAME = 'user1')
    INSERT INTO THANHVIEN (ID, TEN, MANHA, CON, USERNAME, MATKHAU, SOLANSAT, AD)
    VALUES ('TV002', N'Trần Xuân Mẫn', 'NH001', 1, 'user1', '123456', 0, 0);